### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by markenapps** [EinfachHans/cordova-plugin-advanced-background-mode#5]
Hi and thanks a lot for this fork. Unfortunately the ios release build fails.
Could you help please.

XCODE_VERSION=11.3
IOS_PLATFORM_VERSION=5.1.1

`Failed to install 'cordova-plugin-advanced-background-mode': CordovaError: Uh oh!
[21:34:42] File already exists at destination "/private/tmp/download/platforms/ios/That Shopping List/Resources/appbeep.wav" for resource file specified by plugin cordova-plugin-advanced-background-mode in iOS platform
[21:34:42]     at install (/private/tmp/download/platforms/ios/cordova/lib/plugman/pluginHandlers.js:64:23)
[21:34:42]     at ActionStack.process (/private/tmp/download/node_modules/cordova-common/src/ActionStack.js:56:25)
[21:34:42]     at PluginManager.doOperation (/private/tmp/download/node_modules/cordova-common/src/PluginManager.js:114:20)
[21:34:42]     at PluginManager.addPlugin (/private/tmp/download/node_modules/cordova-common/src/PluginManager.js:144:17)
[21:34:42]     at Api.addPlugin (/private/tmp/download/platforms/ios/cordova/Api.js:245:10)
[21:34:42]     at handleInstall (/Users/builder/n/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:581:10)
[21:34:42]     at /Users/builder/n/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:349:28
[21:34:42]     at process._tickCallback (internal/process/next_tick.js:68:7)
[21:34:42] Failed to restore plugin "cordova-plugin-advanced-background-mode" from config.xml. You might need to try adding it again. Error: Uh oh!
[21:34:42] File already exists at destination "/private/tmp/download/platforms/ios/That Shopping List/Resources/appbeep.wav" for resource file specified by plugin cordova-plugin-advanced-background-mode in iOS platform`

**Comment by EinfachHans** [comment]
This Plugin adds a File **appbeeb.wav** as a Resource. The Error told you it already exists. Do you have a other Plugin that adds the same file?

**Comment by markenapps** [comment]
Thanks for your response.
I'm not sure. Don't think so. This error occurs after switching from cordova-plugin-background-mode to cordova-plugin-advanced-mode.

**Comment by EinfachHans** [comment]
The origina plugin also adds this file. Try removing the **platforms** and **plugins** folder and build again.

**Comment by markenapps** [comment]
Thanks a lot for this solution and your plugin. Good work.
